# Generated by Django 4.0.3 on 2022-03-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('bgtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('picture1', models.CharField(blank=True, max_length=100, null=True)),
                ('picture2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
