# Generated by Django 4.0.3 on 2022-03-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_postsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsection',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postsection',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
