# Generated by Django 4.0.3 on 2022-03-30 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_news_links_alter_news_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category'),
        ),
    ]
