# Generated by Django 4.0.3 on 2022-06-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='enquirytype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
