# Generated by Django 4.0.3 on 2022-03-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_postsection_picture1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herotypefive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('bgtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('herocontent', models.TextField(blank=True, null=True)),
                ('positionhero', models.CharField(blank=True, max_length=20, null=True)),
                ('transani', models.CharField(blank=True, max_length=20, null=True)),
                ('link1', models.CharField(blank=True, max_length=200, null=True)),
                ('link2', models.CharField(blank=True, max_length=200, null=True)),
                ('link3', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('cssclass', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
