# Generated by Django 4.0.3 on 2022-03-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_event_photoevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='EventNews',
        ),
    ]
