# Generated by Django 4.0.3 on 2022-03-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_herotypefive'),
    ]

    operations = [
        migrations.AddField(
            model_name='herotypefive',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
