# Generated by Django 4.0.3 on 2022-07-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
