# Generated by Django 4.0.3 on 2022-03-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_event_eventnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoevent',
            name='imgtitle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='photoevent',
            name='imgtitle2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
