# Generated by Django 4.0.3 on 2022-03-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_herotypefive_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herosix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('bgtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('content1', models.TextField(blank=True, null=True)),
                ('content2', models.TextField(blank=True, null=True)),
                ('content3', models.TextField(blank=True, null=True)),
                ('content4', models.TextField(blank=True, null=True)),
                ('content5', models.TextField(blank=True, null=True)),
                ('content6', models.TextField(blank=True, null=True)),
                ('positionhero', models.CharField(blank=True, max_length=20, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('transani', models.CharField(blank=True, max_length=20, null=True)),
                ('link1', models.CharField(blank=True, max_length=200, null=True)),
                ('link2', models.CharField(blank=True, max_length=200, null=True)),
                ('link3', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('cssclass', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
