# Generated by Django 4.0.3 on 2022-03-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_photoevent_imgtitle_alter_photoevent_imgtitle2'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventnews',
            name='url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
