# Generated by Django 4.0.3 on 2022-03-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_herosix_img1_herosix_img2_herosix_img3_herosix_img4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heroseven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('bgtitle1', models.CharField(blank=True, max_length=50, null=True)),
                ('content1', models.TextField(blank=True, null=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='')),
                ('bgtitle2', models.CharField(blank=True, max_length=50, null=True)),
                ('content2', models.TextField(blank=True, null=True)),
                ('img2', models.ImageField(blank=True, null=True, upload_to='')),
                ('bgtitle3', models.CharField(blank=True, max_length=50, null=True)),
                ('content3', models.TextField(blank=True, null=True)),
                ('img3', models.ImageField(blank=True, null=True, upload_to='')),
                ('bgtitle4', models.CharField(blank=True, max_length=50, null=True)),
                ('content4', models.TextField(blank=True, null=True)),
                ('img4', models.ImageField(blank=True, null=True, upload_to='')),
                ('positionhero', models.CharField(blank=True, max_length=20, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('transani', models.CharField(blank=True, max_length=20, null=True)),
                ('link1', models.CharField(blank=True, max_length=200, null=True)),
                ('link2', models.CharField(blank=True, max_length=200, null=True)),
                ('link3', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('cssclass', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
