# Generated by Django 4.0.3 on 2022-08-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_product_created_at_product_productfea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productslug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
