# Generated by Django 4.0.3 on 2022-03-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_eventnews_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventnews',
            name='ttitle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='eventnews',
            name='eventtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
