# Generated by Django 4.0.3 on 2022-03-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_eventnews_ttitle_alter_eventnews_eventtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventnews',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
