# Generated by Django 4.0.3 on 2022-03-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_eventnews_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoevent',
            name='wowdelay',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
