# Generated by Django 4.0.3 on 2022-03-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_photoevent_wowdelay'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='titlecon',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='wowdelay',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='titles',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
