# Generated by Django 4.0.3 on 2022-08-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_annoucement_andescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='annoucement',
            name='adlink',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
