# Generated by Django 4.0.3 on 2022-08-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_annoucement_adlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
