# Generated by Django 4.0.3 on 2022-08-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_category_catype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catype',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Bursa'), (2, 'Post'), (3, 'Product'), (4, 'News')], null=True),
        ),
    ]
