# Generated by Django 4.0.3 on 2022-11-10 04:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_category_catype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contacttel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
