# Generated by Django 4.0.3 on 2022-11-22 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_contact_contacttel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnoucementMeetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anoncetitle', models.CharField(blank=True, max_length=150, null=True)),
                ('stockname', models.CharField(blank=True, max_length=150, null=True)),
                ('companyname', models.CharField(blank=True, max_length=150, null=True)),
                ('andescription', models.TextField(blank=True, null=True)),
                ('anousetype', models.CharField(blank=True, max_length=50, null=True)),
                ('ansubject', models.CharField(blank=True, max_length=150, null=True)),
                ('adlink', models.CharField(blank=True, max_length=300, null=True)),
                ('andate', models.DateField(blank=True, null=True)),
                ('anslug', models.CharField(blank=True, max_length=200, null=True)),
                ('anpostimg', models.ImageField(blank=True, null=True, upload_to='')),
                ('anmstatus', models.BooleanField(blank=True, null=True)),
                ('ancreated_at', models.DateTimeField(auto_now_add=True)),
                ('anupdated_at', models.DateTimeField(auto_now=True)),
                ('ancategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category')),
            ],
        ),
    ]
