# Generated by Django 4.0.3 on 2022-11-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_annoucementmeetings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catype',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Bursa'), (2, 'Post'), (3, 'Product'), (4, 'News'), (5, 'Meetings')], null=True),
        ),
    ]
