# Generated by Django 4.0.3 on 2023-01-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_contact_contacttel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailaddress', models.CharField(blank=True, max_length=150, null=True)),
                ('newname', models.CharField(blank=True, max_length=150, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
