# Generated by Django 4.0.3 on 2023-01-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='titlecon',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
