# Generated by Django 4.0.3 on 2023-01-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_news_created_at_news_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pressrelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('decs', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
