# Generated by Django 4.0.3 on 2023-01-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_pressrelease_news_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressrelease',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
