# Generated by Django 4.0.3 on 2023-01-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_pressrelease_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pressrelease',
            old_name='date',
            new_name='datess',
        ),
    ]
