# Generated by Django 4.0.3 on 2023-01-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_rename_date_pressrelease_datess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metapro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlcontent', models.CharField(blank=True, max_length=150, null=True)),
                ('typecontent', models.CharField(blank=True, max_length=150, null=True)),
                ('titlecontent', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('imagelink', models.CharField(blank=True, max_length=150, null=True)),
                ('imagewidth', models.CharField(blank=True, max_length=150, null=True)),
                ('imageheight', models.CharField(blank=True, max_length=150, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
